name: Sossoldi Flutter CI

on:
  schedule:
    - cron: "0 0 * * 1"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: stable
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
        
      - run: |
          flutter pub get
          flutter test
          flutter build apk
          flutter build appbundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
